// Code generated by MockGen. DO NOT EDIT.
// Source: clock.go
//
// Generated by this command:
//
//	mockgen -destination=../mock/clock.go -package mock -typed -source clock.go
//
// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockClock) Parse(layout, value string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", layout, value)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockClockMockRecorder) Parse(layout, value any) *ClockParseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockClock)(nil).Parse), layout, value)
	return &ClockParseCall{Call: call}
}

// ClockParseCall wrap *gomock.Call
type ClockParseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ClockParseCall) Return(arg0 time.Time, arg1 error) *ClockParseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ClockParseCall) Do(f func(string, string) (time.Time, error)) *ClockParseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ClockParseCall) DoAndReturn(f func(string, string) (time.Time, error)) *ClockParseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Since mocks base method.
func (m *MockClock) Since(t time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", t)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since.
func (mr *MockClockMockRecorder) Since(t any) *ClockSinceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockClock)(nil).Since), t)
	return &ClockSinceCall{Call: call}
}

// ClockSinceCall wrap *gomock.Call
type ClockSinceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ClockSinceCall) Return(arg0 time.Duration) *ClockSinceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ClockSinceCall) Do(f func(time.Time) time.Duration) *ClockSinceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ClockSinceCall) DoAndReturn(f func(time.Time) time.Duration) *ClockSinceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
